name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]  # mainブランチにpushされたときに実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: my-app

      # 2. Node.jsのバージョンをセットアップ
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm install
        working-directory: my-app

      # 4. ビルド (Viteならデフォルトで "build" スクリプト)
      - name: Build
        run: npm run build
        working-directory: my-app

      # 5. Azure App Service へのデプロイ
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myKonvaApp-20250302'  # az webapp create --name で指定した名前
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'my-app/build'  # Viteのビルド成果物ディレクトリ (CRAなら './build')
